Create signUp layout
yuuming/Insta pull request #2
Opened 2018-01-24 02:43 UTC by yuuming

Signup  のレイアウトを作りました。　確認お願いします。

2018-01-24 02:49 UTC, kentoapps requested changes
コメントしたので確認して修正してください

2018-01-24 02:49 UTC, kentoapps commented on app/src/main/res/layout/activity_sign_up.xml
> +        android:id="@+id/email"
１個めはusenameです

2018-01-24 02:49 UTC, kentoapps commented on app/src/main/res/layout/activity_sign_up.xml
> +        android:id="@+id/username"
emailです

2018-01-24 02:49 UTC, kentoapps commented on app/src/main/res/layout/activity_sign_up.xml
> +        android:id="@+id/signup_email"
passwordです

2018-01-24 02:49 UTC, kentoapps commented on app/src/main/res/layout/activity_sign_up.xml
> +        android:hint="@string/username"
passwordです

2018-01-24 02:49 UTC, kentoapps commented on app/src/main/res/layout/activity_sign_up.xml
> +        android:id="@+id/signup_password"
password_confirmです

2018-01-24 03:12 UTC, kentoapps approved these changes

2018-01-24 03:13 UTC, yuuming commented on app/src/main/res/layout/activity_sign_up.xml
> +        android:hint="@string/username"
@kentoapps 
修正しました。
確認宜しくお願いします。

via 99007e1

2018-01-24 03:15 UTC, kentoapps requested changes

2018-01-24 03:15 UTC, kentoapps commented on app/src/main/res/layout/activity_sign_up.xml
> +        android:id="@+id/username"
すべてのEditTextを１行だけ入力できるようにしてください

2018-01-24 03:15 UTC, kentoapps commented on app/src/main/res/layout/activity_sign_up.xml
> +        android:id="@+id/email"
inputTypeをemailadressにしてください

2018-01-24 03:15 UTC, kentoapps commented on app/src/main/res/layout/activity_sign_up.xml
> +        android:id="@+id/password"
inputTypeをpasswordにしてください

2018-01-24 20:13 UTC, yuuming commented on app/src/main/res/layout/activity_sign_up.xml
> +        android:id="@+id/username"
@kentoapps 
 修正しました。確認宜しくお願いします。
3c2329a

2018-01-24 20:14 UTC, yuuming commented on app/src/main/res/layout/activity_sign_up.xml
> +        android:id="@+id/email"
inputType をemailaddressに変更しました。
3c2329a

2018-01-24 20:14 UTC, yuuming commented on app/src/main/res/layout/activity_sign_up.xml
> +        android:id="@+id/password"
inputTypeをpasswordに変更しました。
3c2329a

2018-01-25 03:49 UTC, kentoapps requested changes

2018-01-25 03:49 UTC, kentoapps commented on app/src/main/res/layout/activity_sign_up.xml
> +        android:inputType="text"
ConfirmもtextPasswordにしてください
（これパスワード確認用のEditTextだから。わかりにくかったらConfirm PasswordとかRe-type Passwordとかに変えていいよ！）

2018-01-25 04:12 UTC, kentoapps commented
LGTM 👍

2018-01-25 04:12 UTC, kentoapps approved these changes

2018-01-25 04:13 UTC, yuuming commented on app/src/main/res/layout/activity_sign_up.xml
> +        android:inputType="text"
言われなくてもよく考えるべきでした。😣　みてくれてありがとう☺　4848478

2018-01-25 04:14 UTC, merged